from __future__ import annotations

DATA_PATH = "../data/harryEn/"
SEQ_LEN = 256
BATCH_SIZE = 64
NUM_BATCHES = 50000
VALIDATION_SPLIT = 0.1
VALIDATION_EVERY = 100
VALIDATION_BATCHES = 20

N_LAYERS = 6
N_HEADS = 6
EMBED_SIZE = 192
MLP_HIDDEN_SIZE = EMBED_SIZE * 4
DROPOUT = 0.1

LEARNING_RATE = 5e-4
GRADIENT_CLIPPING = 1.0

CHECKPOINT_DIR = "../checkpoints"
CHECKPOINT_EVERY = 500

RESUME_FROM_CHECKPOINT = None
RESUMED_LEARNING_RATE = None

SAMPLE_PREFIX = "Hello"
SAMPLE_TOKENS = 500
SAMPLE_EVERY = 100
SAMPLE_TEMPERATURE = 1.0
SAMPLE_TOPK = 5
